version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 30502024
      MYSQL_DATABASE: agenda
      MYSQL_USER: admin3050
      MYSQL_PASSWORD: 3050
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: